name: Label issues
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'unread'

      - name: test-toggle-label
        uses: wxh16144/issues-helper@wuxh/feat-toggle_labels
        if: (contains(github.event.issue.body, 'auto-close') == true)
        with:
          actions: "toggle-labels,close-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "unread,label,label-1,label-2"
