name: PR Preview

# on:
#   pull_request_target:
#     types: [opened, synchronize, reopened]

on:
  workflow_dispatch:
    inputs:
      build_res:
        description: "构建结果"
        type: number
        required: true
        default: 1
      test_res:
        description: "测试结果"
        type: number
        required: true
        default: 1
      deploy_res:
        description: "部署结果"
        type: number
        required: true
        default: 1

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preview-start:
    name: start
    runs-on: ubuntu-latest
    steps:
      - name: input
        run: echo 'start'

  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 1

  build-site:
    name: build preview
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: input
        run: exit ${{ inputs.build_res }}

  site-test:
    name: site E2E test
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: input
        run: exit ${{ inputs.test_res }}

  preview-deploy:
    name: deploy preview
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: input
        run: exit ${{ inputs.deploy_res }}

  preview-end:
    name: build preview result
    runs-on: ubuntu-latest
    needs:
      - build-site
      - preview-deploy
    if: always()
    steps:
      - name: success comment
        if: needs.build-site.result == 'success' && needs.preview-deploy.result == 'success'
        run: echo "success"

      - name: failed comment
        if: needs.build-site.result == 'failure' || needs.preview-deploy.result == 'failure'
        run: echo "failed"
