name: Issues Comment

on:
  issues:
    types: [opened, edited, deleted]

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest
    # permissions:
    #   pull-requests: write
    #   contents: write
    steps:
      - name: print event
        run: echo ${{ toJson(github.event) }}
