name: Uploading Release assets

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      
      - name: Build tarball
        run: |
          tar -czf ./website.tar.gz --transform 's|^|${{ github.ref_name}}/|' docs

      - name: Test
        run: |
          cat Release.txt
          ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files:  |
            Release.txt
            website.tar.gz
