name: Download artifact

on:
  workflow_run:
    workflows: ["Upload artifact"]
    types:
      - completed

permissions:
  contents: read

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: my-artifact

      - name: View Directory tree
        run: |
          ls -R
