name: Upgrade Dependencies

on:
  schedule:
    - cron: "0 18 * * *" # every day at 18:00 UTC
    # - timezone: Asia/Shanghai # not supported yet https://github.com/orgs/community/discussions/13454
  workflow_dispatch:

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      pull-requests: write  # for peter-evans/create-pull-request to create PRs
      contents: write       # for git push
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            .ncurc.js
            package.json

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: upgrade deps
        id: upgrade
        run: |
          result=$(npx npm-check-updates -u --jsonUpgraded) 2>&1 || true
          jsonStr=$(echo "$result" | jq -c . | jq -R .)
          echo "result=$jsonStr" >> $GITHUB_OUTPUT

      - name: check if package.json changed
        id: check
        run: |
          if [[ -z $(git status -s package.json) ]]; then
            echo "### changed :robot:" >> $GITHUB_STEP_SUMMARY
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "### not changed :robot:" >> $GITHUB_STEP_SUMMARY
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: gen branch name
        if: ${{ always() }}
        id: branch
        run: |
          echo "name=upgrade-deps/patch-$(date +%Y%m%d_%H_%M)" >> $GITHUB_OUTPUT

      - name: commit changes
        if: ${{ steps.check.outputs.changed == 'true' }}
        id: commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add package.json
          git commit -m "chore: upgrade deps"
          git push origin HEAD:${{ steps.branch.outputs.name }}

      - name: create pull request
        if: ${{ steps.commit.outcome == 'success' }}
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Cannot be default!!!
          # assignees: 'afc163, zombieJ, xrkffgg, MadCcc'
          assignees: 'Wxh16144'
          title: 'chore: upgrade deps'
          body: |
            Upgrade dependencies

            ```json
            ${{ fromJSON(steps.upgrade.outputs.result) }}
            ```
          branch: ${{ steps.branch.outputs.name }}
          delete-branch: true
